In [ ]:
import pandas as pd
import numpy as np

from scipy.stats import spearmanr, kendalltau

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving phase2_results.xlsx to phase2_results.xlsx

In [ ]:
# =========================
# CONFIGURATION
# =========================

INPUT_FILE = "phase2_results.xlsx"
OUTPUT_FILE = "phase3_results.xlsx"

MODEL_COLUMN = "Model"
CONSENSUS_COLUMN = "Consensus_Rank"

RANK_COLUMNS = [
    "MARCOS",
    "SECA",
    "MUTRISS",
    "MAIRCA",
    "CODAS",
    "RAFSI",
    "CRADIS",
    "CoCoSo",
    "MABAC",
    "COPRAS",
    "RAM",
    "WASPAS",
    "PIV",
    "WISP"
]

In [ ]:
df = pd.read_excel(INPUT_FILE)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (968, 24)

Columns:
['Model', 'Price (INR)', 'RAM (GB)', 'Battery (mAh)', 'Camera (MP)', 'Display (Inches)', 'MARCOS', 'SECA', 'MUTRISS', 'MAIRCA', 'CODAS', 'RAFSI', 'CRADIS', 'CoCoSo', 'MABAC', 'COPRAS', 'RAM', 'WASPAS', 'PIV', 'WISP', 'Average_Rank', 'Borda_Count', 'Median_Rank', 'Overall_Consensus_Rank']

In [ ]:
# ============================
# Validate Required Columns
# ============================

MODEL_COLUMN = "Model"

CONSENSUS_COLUMN = "Overall_Consensus_Rank"

RANK_COLUMNS = [
    "MARCOS",
    "SECA",
    "MUTRISS",
    "MAIRCA",
    "CODAS",
    "RAFSI",
    "CRADIS",
    "CoCoSo",
    "MABAC",
    "COPRAS",
    "RAM",
    "WASPAS",
    "PIV",
    "WISP"
]

required_columns = [MODEL_COLUMN, CONSENSUS_COLUMN] + RANK_COLUMNS

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:
    raise ValueError(f"Missing columns: {missing_columns}")

print("✅ Data validation successful.")

✅ Data validation successful.

In [ ]:
#step 10

spearman_matrix = pd.DataFrame(
    index=RANK_COLUMNS,
    columns=RANK_COLUMNS,
    dtype=float
)

for method1 in RANK_COLUMNS:
    for method2 in RANK_COLUMNS:

        correlation, _ = spearmanr(
            df[method1],
            df[method2]
        )

        spearman_matrix.loc[
            method1,
            method2
        ] = correlation

print("Spearman Correlation Matrix:")
display(spearman_matrix)

Spearman Correlation Matrix:

,MARCOS,SECA,MUTRISS,MAIRCA,CODAS,RAFSI,CRADIS,CoCoSo,MABAC,COPRAS,RAM,WASPAS,PIV,WISP
MARCOS,1.000000,0.971213,0.983443,0.971213,0.997229,0.955485,1.000000,0.898404,1.000000,0.785195,0.985307,0.976476,0.909760,0.598491
SECA,0.971213,1.000000,0.977926,1.000000,0.961384,0.881829,0.971213,0.952923,0.971213,0.767796,0.986573,0.989955,0.975170,0.702694
MUTRISS,0.983443,0.977926,1.000000,0.977926,0.973036,0.914594,0.983443,0.936690,0.983443,0.797318,0.993336,0.988511,0.941420,0.672258
MAIRCA,0.971213,1.000000,0.977926,1.000000,0.961384,0.881829,0.971213,0.952923,0.971213,0.767796,0.986573,0.989955,0.975170,0.702694
CODAS,0.997229,0.961384,0.973036,0.961384,1.000000,0.963497,0.997229,0.877112,0.997229,0.779585,0.974881,0.964622,0.892421,0.566471
RAFSI,0.955485,0.881829,0.914594,0.881829,0.963497,1.000000,0.955485,0.776340,0.955485,0.694440,0.907205,0.888929,0.787150,0.410004
CRADIS,1.000000,0.971213,0.983443,0.971213,0.997229,0.955485,1.000000,0.898404,1.000000,0.785195,0.985307,0.976476,0.909760,0.598491
CoCoSo,0.898404,0.952923,0.936690,0.952923,0.877112,0.776340,0.898404,1.000000,0.898404,0.733556,0.950366,0.965557,0.978204,0.851319
MABAC,1.000000,0.971213,0.983443,0.971213,0.997229,0.955485,1.000000,0.898404,1.000000,0.785195,0.985307,0.976476,0.909760,0.598491
COPRAS,0.785195,0.767796,0.797318,0.767796,0.779585,0.694440,0.785195,0.733556,0.785195,1.000000,0.792529,0.789793,0.738472,0.549675
RAM,0.985307,0.986573,0.993336,0.986573,0.974881,0.907205,0.985307,0.950366,0.985307,0.792529,1.000000,0.997797,0.950983,0.695343
WASPAS,0.976476,0.989955,0.988511,0.989955,0.964622,0.888929,0.976476,0.965557,0.976476,0.789793,0.997797,1.000000,0.965231,0.723453
PIV,0.909760,0.975170,0.941420,0.975170,0.892421,0.787150,0.909760,0.978204,0.909760,0.738472,0.950983,0.965231,1.000000,0.793637
WISP,0.598491,0.702694,0.672258,0.702694,0.566471,0.410004,0.598491,0.851319,0.598491,0.549675,0.695343,0.723453,0.793637,1.000000

In [ ]:
# step 11
kendall_matrix = pd.DataFrame(
    index=RANK_COLUMNS,
    columns=RANK_COLUMNS,
    dtype=float
)

for method1 in RANK_COLUMNS:
    for method2 in RANK_COLUMNS:

        tau, _ = kendalltau(
            df[method1],
            df[method2]
        )

        kendall_matrix.loc[
            method1,
            method2
        ] = tau

print("Kendall's Tau Matrix:")
display(kendall_matrix)

Kendall's Tau Matrix:

,MARCOS,SECA,MUTRISS,MAIRCA,CODAS,RAFSI,CRADIS,CoCoSo,MABAC,COPRAS,RAM,WASPAS,PIV,WISP
MARCOS,1.000000,0.904134,0.909168,0.904134,0.965848,0.849432,1.000000,0.753310,1.000000,0.732157,0.912236,0.889007,0.807341,0.437089
SECA,0.904134,1.000000,0.893878,1.000000,0.875631,0.770215,0.904134,0.826664,0.904134,0.722363,0.928688,0.927842,0.893079,0.516196
MUTRISS,0.909168,0.893878,1.000000,0.893878,0.878665,0.771249,0.909168,0.811674,0.909168,0.762001,0.940508,0.921706,0.849022,0.498274
MAIRCA,0.904134,1.000000,0.893878,1.000000,0.875631,0.770215,0.904134,0.826664,0.904134,0.722363,0.928688,0.927842,0.893079,0.516196
CODAS,0.965848,0.875631,0.878665,0.875631,1.000000,0.867987,0.965848,0.721722,0.965848,0.705800,0.879435,0.856889,0.775428,0.411954
RAFSI,0.849432,0.770215,0.771249,0.770215,0.867987,1.000000,0.849432,0.612758,0.849432,0.588076,0.768463,0.744515,0.672139,0.287479
CRADIS,1.000000,0.904134,0.909168,0.904134,0.965848,0.849432,1.000000,0.753310,1.000000,0.732157,0.912236,0.889007,0.807341,0.437089
CoCoSo,0.753310,0.826664,0.811674,0.826664,0.721722,0.612758,0.753310,1.000000,0.753310,0.653320,0.839595,0.864303,0.883263,0.664798
MABAC,1.000000,0.904134,0.909168,0.904134,0.965848,0.849432,1.000000,0.753310,1.000000,0.732157,0.912236,0.889007,0.807341,0.437089
COPRAS,0.732157,0.722363,0.762001,0.722363,0.705800,0.588076,0.732157,0.653320,0.732157,1.000000,0.775394,0.761967,0.688480,0.412035
RAM,0.912236,0.928688,0.940508,0.928688,0.879435,0.768463,0.912236,0.839595,0.912236,0.775394,1.000000,0.969865,0.876251,0.517563
WASPAS,0.889007,0.927842,0.921706,0.927842,0.856889,0.744515,0.889007,0.864303,0.889007,0.761967,0.969865,1.000000,0.895096,0.540160
PIV,0.807341,0.893079,0.849022,0.893079,0.775428,0.672139,0.807341,0.883263,0.807341,0.688480,0.876251,0.895096,1.000000,0.608494
WISP,0.437089,0.516196,0.498274,0.516196,0.411954,0.287479,0.437089,0.664798,0.437089,0.412035,0.517563,0.540160,0.608494,1.000000

In [ ]:
#step 12
def calculate_top_k_agreement(
    data,
    method_column,
    consensus_column,
    model_column,
    k
):
    consensus_top_k = set(
        data.sort_values(consensus_column)
            .head(k)[model_column]
    )

    method_top_k = set(
        data.sort_values(method_column)
            .head(k)[model_column]
    )

    overlap = len(
        consensus_top_k.intersection(method_top_k)
    )

    agreement = overlap / k

    return overlap, agreement

In [ ]:
top_k_results = []

for method in RANK_COLUMNS:

    overlap_10, agreement_10 = calculate_top_k_agreement(
        df,
        method,
        CONSENSUS_COLUMN,
        MODEL_COLUMN,
        10
    )

    overlap_20, agreement_20 = calculate_top_k_agreement(
        df,
        method,
        CONSENSUS_COLUMN,
        MODEL_COLUMN,
        20
    )

    top_k_results.append({
        "Method": method,
        "Top10_Overlap": overlap_10,
        "Top10_Agreement_%": agreement_10 * 100,
        "Top20_Overlap": overlap_20,
        "Top20_Agreement_%": agreement_20 * 100
    })

top_k_df = pd.DataFrame(top_k_results)

display(top_k_df)

,Method,Top10_Overlap,Top10_Agreement_%,Top20_Overlap,Top20_Agreement_%
0,MARCOS,5,50.0,16,80.0
1,SECA,10,100.0,18,90.0
2,MUTRISS,5,50.0,17,85.0
3,MAIRCA,10,100.0,18,90.0
4,CODAS,5,50.0,16,80.0
5,RAFSI,4,40.0,11,55.0
6,CRADIS,5,50.0,16,80.0
7,CoCoSo,10,100.0,17,85.0
8,MABAC,5,50.0,16,80.0
9,COPRAS,6,60.0,13,65.0
10,RAM,6,60.0,17,85.0
11,WASPAS,8,80.0,18,90.0
12,PIV,10,100.0,20,100.0
13,WISP,7,70.0,12,60.0

In [ ]:
# step 13 - rank stability
rank_stability_df = df[
    [MODEL_COLUMN] + RANK_COLUMNS
].copy()

rank_stability_df["Rank_Stability_SD"] = (
    rank_stability_df[RANK_COLUMNS].std(axis=1)
)

rank_stability_df = rank_stability_df.sort_values(
    "Rank_Stability_SD"
)

display(
    rank_stability_df[
        [MODEL_COLUMN, "Rank_Stability_SD"]
    ]
)

                                                Model  Rank_Stability_SD
4    Xiaomi Redmi Note 13 Pro Plus (12GB RAM + 256GB)           1.899971
2               Realme 11 Pro Plus (12GB RAM + 256GB)           2.164905
5    Xiaomi Redmi Note 13 Pro Plus (12GB RAM + 512GB)           2.315737
1                       Honor 90 5G (12GB RAM +512GB)           2.757607
0      Xiaomi Redmi Note 13 Pro 5G (12GB RAM + 256GB)           3.049950
..                                                ...                ...
483                           Samsung Galaxy Z Fold 3         278.062725
490     Samsung Galaxy Z Fold 3 5G (12GB RAM + 512GB)         282.150854
313                           Samsung Galaxy Z Fold 5         303.793561
331        Samsung Galaxy Z Fold 5 (12GB RAM + 512GB)         315.983655
342          Samsung Galaxy Z Fold 5 (12GB RAM + 1TB)         325.828285

[968 rows x 2 columns]

In [ ]:
print("Minimum SD :", rank_stability_df["Rank_Stability_SD"].min())
print("Maximum SD :", rank_stability_df["Rank_Stability_SD"].max())
print("Average SD :", rank_stability_df["Rank_Stability_SD"].mean())

Minimum SD : 1.8999710813299528
Maximum SD : 325.8282851880288
Average SD : 76.17631347332701

In [ ]:
def stability_category(sd):
    if sd <= 25:
        return "High Stability"
    elif sd <= 75:
        return "Moderate Stability"
    else:
        return "Low Stability"

rank_stability_df["Stability_Category"] = (
    rank_stability_df["Rank_Stability_SD"]
    .apply(stability_category)
)

display(rank_stability_df[
    ["Model", "Rank_Stability_SD", "Stability_Category"]
].head(20))

,Model,Rank_Stability_SD,Stability_Category
4,Xiaomi Redmi Note 13 Pro Plus (12GB RAM + 256GB),1.899971,High Stability
2,Realme 11 Pro Plus (12GB RAM + 256GB),2.164905,High Stability
5,Xiaomi Redmi Note 13 Pro Plus (12GB RAM + 512GB),2.315737,High Stability
1,Honor 90 5G (12GB RAM +512GB),2.757607,High Stability
0,Xiaomi Redmi Note 13 Pro 5G (12GB RAM + 256GB),3.049950,High Stability
3,Xiaomi Redmi Note 12 Pro Plus (12GB RAM + 256GB),3.099982,High Stability
10,Xiaomi Redmi Note 12 Pro Plus,3.321591,High Stability
9,Realme 11 Pro Plus,3.451389,High Stability
11,Xiaomi Redmi Note 13 Pro Plus,4.159591,High Stability
8,Honor 90 5G,4.380275,High Stability
7,Xiaomi Redmi Note 13 Pro 5G (8GB RAM + 256GB),4.413391,High Stability
6,Xiaomi Redmi Note 13 Pro 5G,5.049208,High Stability
15,Infinix Zero 30 5G (12GB RAM + 256GB),7.308357,High Stability
16,Xiaomi Redmi Note 13 5G (12GB RAM + 256GB),8.887576,High Stability
17,Realme Narzo 60 Pro (12GB RAM + 256GB),10.483897,High Stability
13,Infinix Zero Ultra,11.110830,High Stability
965,Nokia 225 4G,12.736769,High Stability
19,Realme 11 Pro (12GB RAM + 256GB),12.830253,High Stability
967,Nokia 5310 Dual Sim,12.981813,High Stability
960,Nokia 150 (2020),15.684387,High Stability

In [ ]:
#step 14 - Method Representative Rank

representative_results = []

for method in RANK_COLUMNS:

    other_methods = [
        m for m in RANK_COLUMNS
        if m != method
    ]

    average_correlation = (
        spearman_matrix
        .loc[method, other_methods]
        .mean()
    )

    representative_results.append({
        "Method": method,
        "Average_Spearman_Correlation":
            average_correlation
    })

representative_df = pd.DataFrame(
    representative_results
)

In [ ]:
representative_df[
    "Representative_Rank"
] = representative_df[
    "Average_Spearman_Correlation"
].rank(
    ascending=False,
    method="min"
)

representative_df = representative_df.sort_values(
    "Representative_Rank"
)

display(representative_df)

     Method  Average_Spearman_Correlation  Representative_Rank
11   WASPAS                      0.937941                  1.0
10      RAM                      0.937808                  2.0
2   MUTRISS                      0.932565                  3.0
1      SECA                      0.931530                  4.0
3    MAIRCA                      0.931530                  4.0
8     MABAC                      0.925555                  6.0
6    CRADIS                      0.925555                  6.0
0    MARCOS                      0.925555                  6.0
4     CODAS                      0.915852                  9.0
12      PIV                      0.902088                 10.0
7    CoCoSo                      0.897708                 11.0
5     RAFSI                      0.844021                 12.0
9    COPRAS                      0.751273                 13.0
13     WISP                      0.651002                 14.0

In [ ]:
#final summary

average_spearman = (
    spearman_matrix
    .replace(1.0, np.nan)
    .mean(axis=1)
)

average_kendall = (
    kendall_matrix
    .replace(1.0, np.nan)
    .mean(axis=1)
)

In [ ]:
phase3_summary = representative_df.copy()

phase3_summary["Average_Spearman"] = (
    phase3_summary["Method"]
    .map(average_spearman)
)

phase3_summary["Average_Kendall"] = (
    phase3_summary["Method"]
    .map(average_kendall)
)

phase3_summary = phase3_summary.merge(
    top_k_df[
        [
            "Method",
            "Top10_Agreement_%",
            "Top20_Agreement_%"
        ]
    ],
    on="Method"
)

display(phase3_summary)

,Method,Average_Spearman_Correlation,Representative_Rank,Average_Spearman,Average_Kendall,Top10_Agreement_%,Top20_Agreement_%
0,WASPAS,0.937941,1.0,0.937941,0.852093,80.0,90.0
1,RAM,0.937808,2.0,0.937808,0.858551,60.0,85.0
2,MUTRISS,0.932565,3.0,0.932565,0.842181,50.0,85.0
3,SECA,0.931530,4.0,0.925824,0.838913,100.0,90.0
4,MAIRCA,0.931530,4.0,0.925824,0.838913,100.0,90.0
5,MABAC,0.925555,6.0,0.912020,0.823987,50.0,80.0
6,CRADIS,0.925555,6.0,0.912020,0.823987,50.0,80.0
7,MARCOS,0.925555,6.0,0.912020,0.823987,50.0,80.0
8,CODAS,0.915852,9.0,0.915852,0.826668,50.0,80.0
9,PIV,0.902088,10.0,0.902088,0.804335,100.0,100.0
10,CoCoSo,0.897708,11.0,0.897708,0.766515,100.0,85.0
11,RAFSI,0.844021,12.0,0.844021,0.723184,40.0,55.0
12,COPRAS,0.751273,13.0,0.751273,0.691405,60.0,65.0
13,WISP,0.651002,14.0,0.651002,0.483417,70.0,60.0

In [ ]:
with pd.ExcelWriter(OUTPUT_FILE) as writer:

    spearman_matrix.to_excel(
        writer,
        sheet_name="Spearman"
    )

    kendall_matrix.to_excel(
        writer,
        sheet_name="Kendall"
    )

    top_k_df.to_excel(
        writer,
        sheet_name="Top_K_Agreement",
        index=False
    )

    rank_stability_df.to_excel(
        writer,
        sheet_name="Rank_Stability",
        index=False
    )

    representative_df.to_excel(
        writer,
        sheet_name="Representative_Method",
        index=False
    )

    phase3_summary.to_excel(
        writer,
        sheet_name="Phase3_Summary",
        index=False
    )

print(f"Phase 3 results saved to: {OUTPUT_FILE}")

Phase 3 results saved to: phase3_results.xlsx

In [ ]:
from google.colab import files

files.download(OUTPUT_FILE)